import fs from "node:fs/promises";
import type { ChangePackage, LogicalChange, TestEvidence } from "./types.ts";
import { REVIEW_FILES, reviewFile } from "./paths.ts";
import { countEvents, makeEvent, appendEvent, readEventsOfType } from "./events.ts";
import { loadSession, endSession } from "./session.ts";
import { defaultAnalyzer } from "./analyzer.ts";
import { readIntents } from "./intent.ts";
import { listCheckpoints } from "./checkpoints.ts";
import { gitHead, listCommits, diffPatch, currentBranch } from "./git.ts";
import { redactAndTruncate } from "./redact.ts";
import { loadOrCreateConfig } from "./config.ts";
import { renderReview } from "./review.ts";

export interface BuildOptions {
  includeDiff?: boolean | undefined;
  /** Keep the session active after building (default: the build finalizes the session). */
  keepActive?: boolean | undefined;
}

export interface BuildResult {
  changePackage: ChangePackage;
  diff?: string | undefined;
  review: string;
  changePackagePath: string;
  reviewPath: string;
}

/**
 * Reads session + events + git + test evidence and produces the machine-readable
 * Change Package. The human-readable review.md is generated by review.ts on top
 * of the same structure.
 */
export async function buildChangePackage(
  projectRoot: string,
  options: BuildOptions = {},
): Promise<BuildResult> {
  const session = await loadSession(projectRoot);
  if (!session) throw new Error("no review session found — run agent_review_start first");

  const config = await loadOrCreateConfig(projectRoot);
  const includeDiff = options.includeDiff ?? config.includeDiffInPackageByDefault;

  const logicalChanges = await defaultAnalyzer.analyze(projectRoot, session.initialHead ?? undefined);
  const intents = await readIntents(projectRoot, session.id);

  const head = await gitHead(projectRoot);
  const commits =
    session.initialHead && head && session.initialHead !== head
      ? await listCommits(projectRoot, `${session.initialHead}..HEAD`)
      : [];

  const testEvents = await readEventsOfType(projectRoot, "test.completed", session.id);
  const tests = testEvents.map((event) => event.payload as unknown as TestEvidence);

  const risks = computeRisks(session, logicalChanges, tests, intents);
  const limitations = [
    "Snapshots cover only files that were changed at checkpoint time.",
    "Symbol extraction is regex-based, not AST-based.",
    "Only observed facts are recorded — private model reasoning is not captured.",
    ...new Set(intents.flatMap((intent) => intent.limitations)),
  ];

  const toolEvents = await readEventsOfType(projectRoot, "tool.started", session.id);
  const commandEvents = await readEventsOfType(projectRoot, "command.started", session.id);
  const allCheckpoints = await listCheckpoints(projectRoot);

  const changePackage: ChangePackage = {
    schemaVersion: "agent-review/v1",
    session: {
      id: session.id,
      startedAt: session.startedAt,
      endedAt: session.endedAt,
      status: session.status,
    },
    task: session.task,
    branch: (await currentBranch(projectRoot)) ?? session.workingBranch,
    commits,
    changedFiles: logicalChanges,
    logicalChanges: intents,
    tests,
    risks,
    limitations,
    agentMetadata: {
      toolCalls: toolEvents.length,
      commands: commandEvents.length,
      checkpoints: allCheckpoints.filter((cp) => cp.sessionId === session.id).length,
      tests: tests.length,
      events: await countEvents(projectRoot),
    },
    generatedAt: new Date().toISOString(),
  };

  await fs.writeFile(reviewFile(projectRoot, "changePackage"), `${JSON.stringify(changePackage, null, 2)}\n`, "utf8");
  await appendEvent(
    projectRoot,
    makeEvent("change-package.created", "package-builder", { file: REVIEW_FILES.changePackage }, session.id),
  );

  let diff: string | undefined;
  if (includeDiff) {
    const raw = await diffPatch(projectRoot, session.initialHead ?? undefined, 256 * 1024);
    diff = redactAndTruncate(raw, 256 * 1024).text;
  }

  if (!options.keepActive) {
    await endSession(projectRoot, "ended");
    changePackage.session.status = "ended";
    changePackage.session.endedAt = new Date().toISOString();
    await fs.writeFile(reviewFile(projectRoot, "changePackage"), `${JSON.stringify(changePackage, null, 2)}\n`, "utf8");
  }

  const review = renderReview(changePackage, diff);
  await fs.writeFile(reviewFile(projectRoot, "review"), review, "utf8");
  await appendEvent(
    projectRoot,
    makeEvent("review.generated", "review", { file: REVIEW_FILES.review }, session.id),
  );

  return {
    changePackage,
    diff,
    review,
    changePackagePath: reviewFile(projectRoot, "changePackage"),
    reviewPath: reviewFile(projectRoot, "review"),
  };
}

function computeRisks(
  session: { dirtyAtStart: string[]; initialBranch: string; workingBranch: string },
  changes: LogicalChange[],
  tests: TestEvidence[],
  intents: Awaited<ReturnType<typeof readIntents>>,
): string[] {
  const risks: string[] = [];
  if (session.dirtyAtStart.length > 0) {
    risks.push(`Working tree was dirty at session start (${session.dirtyAtStart.length} entries) — pre-existing changes may be mixed into the diff.`);
  }
  const failed = tests.filter((test) => test.status !== "passed");
  if (failed.length > 0) {
    risks.push(`${failed.length} test run(s) did not pass (exit codes: ${failed.map((t) => t.exitCode ?? "signal").join(", ")}).`);
  }
  if (tests.length === 0) {
    risks.push("No test evidence was recorded for this session.");
  }
  const highRisk = intents.filter((intent) => intent.risk === "high");
  if (highRisk.length > 0) {
    risks.push(`${highRisk.length} intent(s) marked high risk: ${highRisk.map((i) => i.entity).join(", ")}.`);
  }
  if (session.initialBranch !== session.workingBranch && /^(main|master|develop)$/.test(session.initialBranch)) {
    risks.push(`Branch was created from protected branch "${session.initialBranch}".`);
  }
  const totalInsertions = changes.reduce((sum, change) => sum + change.insertions, 0);
  if (totalInsertions > 2000) {
    risks.push(`Large diff: ${totalInsertions} insertions across ${changes.length} files.`);
  }
  const removals = changes.filter((change) => change.kind === "removed");
  if (removals.length > 0) {
    risks.push(`${removals.length} file(s) removed: ${removals.map((c) => c.path).join(", ")}.`);
  }
  return risks;
}
